sliding_window_find_maximum: sliding_window_maximum.o
	g++ sliding_window_maximum.o -o sliding_window_find_maximum

sliding_window_maximum.o: sliding_window_maximum.cpp
	g++ -c -g -std=c++11 sliding_window_maximum.cpp

clean:
	rm *.o sliding_window_find_maximum
