uncaught_error_exception_test: uncaught_error_exception_test.o
	g++ uncaught_error_exception_test.o -std=c++11 -o uncaught_error_exception_test

uncaught_error_exception_test.o: uncaught_error_exception_test.cpp
	g++ -c -g -std=c++11 uncaught_error_exception_test.cpp

clean:
	rm *.o uncaught_error_exception_test