andoliunll: main.o anil_doubly_linked_unsorted_ll.o
	g++ main.o anil_doubly_linked_unsorted_ll.o -o andoliunll

main.o: main.cpp
	g++ -c -g main.cpp

anil_doubly_linked_unsorted_ll.o: anil_doubly_linked_unsorted_ll.cpp anil_doubly_linked_unsorted_ll.h
	g++ -c -g anil_doubly_linked_unsorted_ll.cpp

clean:
	rm *.o andoliunll